"""Disclaimer middleware.

Week 12: Extracted from main.py God Object
"""

from fastapi import Request
from fastapi.responses import JSONResponse
import json
import logging

logger = logging.getLogger(__name__)

LEGAL_DISCLAIMER = {
    "text": (
        "This analysis is generated by an AI system and is provided for informational "
        "and educational purposes only. It does NOT constitute investment advice, "
        "financial advice, trading advice, or any other form of professional advice. "
        "AI-generated analysis may contain errors, hallucinations, or outdated information. "
        "Always consult a qualified financial advisor before making investment decisions. "
        "Past performance does not guarantee future results."
    ),
    "ai_disclosure": (
        "This content was generated by artificial intelligence (LLM-based multi-agent "
        "debate system). The system uses multiple AI models that may disagree with each "
        "other. Confidence scores reflect model agreement, NOT probability of accuracy."
    ),
    "data_sources_notice": (
        "Market data sourced from public APIs (yfinance, FRED). Data may be delayed, "
        "incomplete, or inaccurate. VeriFind does not guarantee data accuracy or completeness."
    ),
    "no_liability": (
        "VeriFind, its creators, and contributors accept no liability for any losses "
        "or damages arising from the use of this analysis."
    ),
    "version": "2.0",
    "effective_date": "2026-02-14",
    "regulatory_references": [
        "SEC Investment Advisers Act §202(a)(11)",
        "SEC AI Washing Enforcement (2024-2026)",
        "EU AI Act - High-Risk AI Systems"
    ]
}


async def add_disclaimer_to_json_responses(request: Request, call_next):
    """
    Add legal disclaimer to all JSON responses.
    
    Week 11 Day 3: Legal compliance requirement.
    """
    response = await call_next(request)
    
    # Only add disclaimer to JSON responses
    if response.headers.get("content-type", "").startswith("application/json"):
        # Skip for health/metrics endpoints
        if request.url.path in ["/health", "/metrics", "/docs", "/redoc", "/openapi.json"]:
            return response
        
        # Read response body
        response_body = b""
        async for chunk in response.body_iterator:
            response_body += chunk
        
        try:
            # Parse JSON
            data = json.loads(response_body.decode())
            
            # Add disclaimer if not already present
            if isinstance(data, dict) and "disclaimer" not in data:
                data["disclaimer"] = LEGAL_DISCLAIMER
            
            # Re-encode response with correct Content-Length
            new_headers = dict(response.headers)
            new_headers.pop("content-length", None)  # Remove old Content-Length
            
            return JSONResponse(
                content=data,
                status_code=response.status_code,
                headers=new_headers,
                media_type="application/json"
            )
        except (json.JSONDecodeError, UnicodeDecodeError):
            # If not valid JSON, return original response
            return JSONResponse(
                content=response_body.decode(),
                status_code=response.status_code,
                headers=dict(response.headers)
            )
    
    return response
