"""
Integration tests for Neo4j Graph Storage.

Week 3 Day 4: Store Episodes, VerifiedFacts, and their lineage in Neo4j.

Graph Schema:
- Episode nodes: query_id, query_text, created_at
- VerifiedFact nodes: fact_id, status, extracted_values, created_at
- Relationships: (:Episode)-[:GENERATED]->(:VerifiedFact)
- Lineage tracking: (:VerifiedFact)-[:DERIVED_FROM]->(:VerifiedFact)

Success criteria:
- Create Episode and VerifiedFact nodes
- Link Episode to VerifiedFacts
- Query facts by Episode
- Trace lineage backward (which facts led to this conclusion)
- Cypher queries for audit trail
"""

import pytest
import os
from datetime import datetime, UTC
from typing import Dict, Any

from src.graph.neo4j_client import Neo4jGraphClient
from src.truth_boundary.gate import VerifiedFact


# ==============================================================================
# Integration Tests (require Neo4j running)
# ==============================================================================

@pytest.fixture
def neo4j_client():
    """Create Neo4j client connection."""
    neo4j_password = os.getenv("NEO4J_PASSWORD")
    if not neo4j_password:
        pytest.skip("NEO4J_PASSWORD is not set for integration tests")

    client = Neo4jGraphClient(
        uri='neo4j://localhost:7688',
        user='neo4j',
        password=neo4j_password
    )

    # Clean up before tests
    client.clear_all()  # For testing only

    yield client

    # Cleanup after tests
    client.close()


def test_neo4j_initialization(neo4j_client):
    """Test Neo4j client initializes correctly."""
    assert neo4j_client is not None
    assert neo4j_client.is_connected()


def test_create_episode_node(neo4j_client):
    """Test creating Episode node."""
    episode_id = 'episode_001'
    query_text = 'Calculate correlation between SPY and QQQ'

    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text=query_text,
        created_at=datetime.now(UTC)
    )

    # Verify created
    episode = neo4j_client.get_episode(episode_id)

    assert episode is not None
    assert episode['episode_id'] == episode_id
    assert episode['query_text'] == query_text


def test_create_verified_fact_node(neo4j_client):
    """Test creating VerifiedFact node."""
    fact = VerifiedFact(
        fact_id='fact_neo4j_001',
        query_id='query_neo4j_001',
        plan_id='plan_neo4j_001',
        code_hash='abc123',
        status='success',
        extracted_values={'correlation': 0.95},
        execution_time_ms=1500,
        memory_used_mb=50.0,
        created_at=datetime.now(UTC)
    )

    neo4j_client.create_verified_fact_node(fact)

    # Verify created
    retrieved = neo4j_client.get_fact_node(fact.fact_id)

    assert retrieved is not None
    assert retrieved['fact_id'] == fact.fact_id
    assert retrieved['status'] == 'success'


def test_link_episode_to_fact(neo4j_client):
    """Test creating GENERATED relationship."""
    # Create Episode
    episode_id = 'episode_link_001'
    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text='Test query',
        created_at=datetime.now(UTC)
    )

    # Create VerifiedFact
    fact = VerifiedFact(
        fact_id='fact_link_001',
        query_id=episode_id,
        plan_id='plan_001',
        code_hash='hash_001',
        status='success',
        extracted_values={'value': 42},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact)

    # Link them
    neo4j_client.link_episode_to_fact(episode_id, fact.fact_id)

    # Verify relationship exists
    facts = neo4j_client.get_facts_for_episode(episode_id)

    assert len(facts) == 1
    assert facts[0]['fact_id'] == fact.fact_id


def test_query_facts_for_episode(neo4j_client):
    """Test querying all facts generated by an Episode."""
    episode_id = 'episode_multi_001'
    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text='Multi-fact query',
        created_at=datetime.now(UTC)
    )

    # Create multiple facts
    for i in range(3):
        fact = VerifiedFact(
            fact_id=f'fact_multi_{i}',
            query_id=episode_id,
            plan_id=f'plan_{i}',
            code_hash=f'hash_{i}',
            status='success',
            extracted_values={'value': i * 10},
            execution_time_ms=1000,
            memory_used_mb=30.0,
            created_at=datetime.now(UTC)
        )
        neo4j_client.create_verified_fact_node(fact)
        neo4j_client.link_episode_to_fact(episode_id, fact.fact_id)

    # Query all facts
    facts = neo4j_client.get_facts_for_episode(episode_id)

    assert len(facts) == 3
    assert all(f['fact_id'].startswith('fact_multi_') for f in facts)


def test_lineage_tracking(neo4j_client):
    """Test tracking lineage: Fact B derived from Fact A."""
    # Create two facts
    fact_a = VerifiedFact(
        fact_id='fact_a',
        query_id='query_lineage',
        plan_id='plan_a',
        code_hash='hash_a',
        status='success',
        extracted_values={'base_value': 100},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )

    fact_b = VerifiedFact(
        fact_id='fact_b',
        query_id='query_lineage',
        plan_id='plan_b',
        code_hash='hash_b',
        status='success',
        extracted_values={'derived_value': 200},
        execution_time_ms=1500,
        memory_used_mb=40.0,
        created_at=datetime.now(UTC)
    )

    neo4j_client.create_verified_fact_node(fact_a)
    neo4j_client.create_verified_fact_node(fact_b)

    # Create DERIVED_FROM relationship
    neo4j_client.create_lineage(from_fact_id='fact_b', to_fact_id='fact_a')

    # Query lineage
    ancestors = neo4j_client.get_fact_lineage(fact_b.fact_id)

    assert len(ancestors) == 1
    assert ancestors[0]['fact_id'] == 'fact_a'


def test_cypher_query_for_audit_trail(neo4j_client):
    """Test running Cypher query to trace full audit trail."""
    # Create Episode → VerifiedFacts chain
    episode_id = 'audit_episode'
    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text='Audit trail test',
        created_at=datetime.now(UTC)
    )

    fact_1 = VerifiedFact(
        fact_id='audit_fact_1',
        query_id=episode_id,
        plan_id='plan_1',
        code_hash='hash_1',
        status='success',
        extracted_values={'step': 1},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact_1)
    neo4j_client.link_episode_to_fact(episode_id, fact_1.fact_id)

    # Run Cypher query
    query = """
    MATCH (e:Episode {episode_id: $episode_id})-[:GENERATED]->(f:VerifiedFact)
    RETURN e, f
    """
    results = neo4j_client.run_cypher(query, {'episode_id': episode_id})

    assert len(results) > 0
    assert 'e' in results[0]
    assert 'f' in results[0]


def test_delete_episode_and_facts(neo4j_client):
    """Test deleting Episode and its related facts."""
    episode_id = 'delete_episode'
    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text='Delete test',
        created_at=datetime.now(UTC)
    )

    fact = VerifiedFact(
        fact_id='delete_fact',
        query_id=episode_id,
        plan_id='plan_delete',
        code_hash='hash_delete',
        status='success',
        extracted_values={'value': 99},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact)
    neo4j_client.link_episode_to_fact(episode_id, fact.fact_id)

    # Delete Episode and all related facts
    neo4j_client.delete_episode(episode_id)

    # Verify deleted
    episode = neo4j_client.get_episode(episode_id)
    assert episode is None

    # Facts should also be deleted (CASCADE)
    fact_node = neo4j_client.get_fact_node(fact.fact_id)
    assert fact_node is None


def test_graph_stats(neo4j_client):
    """Test getting graph statistics."""
    # Create some nodes
    neo4j_client.create_episode(
        episode_id='stats_episode',
        query_text='Stats test',
        created_at=datetime.now(UTC)
    )

    fact = VerifiedFact(
        fact_id='stats_fact',
        query_id='stats_episode',
        plan_id='plan_stats',
        code_hash='hash_stats',
        status='success',
        extracted_values={'value': 777},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact)
    neo4j_client.link_episode_to_fact('stats_episode', fact.fact_id)

    # Get stats
    stats = neo4j_client.get_graph_stats()

    assert stats['episode_count'] >= 1
    assert stats['fact_count'] >= 1
    assert stats['relationship_count'] >= 1


def test_create_and_link_synthesis(neo4j_client):
    """Test creating Synthesis node and linking to fact."""
    fact = VerifiedFact(
        fact_id='synthesis_fact',
        query_id='synthesis_query',
        plan_id='synthesis_plan',
        code_hash='hash_synth',
        status='success',
        extracted_values={'ticker': 'AAPL', 'price': 123.45},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC),
        statement='AAPL price is 123.45'
    )
    neo4j_client.create_verified_fact_node(fact)

    synthesis_id = neo4j_client.create_synthesis_node(
        fact_id=fact.fact_id,
        synthesis_data={
            'balanced_view': 'Balanced summary',
            'recommendation': 'Hold',
            'original_confidence': 0.80,
            'adjusted_confidence': 0.82,
            'key_risks': ['Valuation risk'],
            'key_opportunities': ['Growth momentum']
        }
    )
    neo4j_client.link_fact_to_synthesis(fact.fact_id, synthesis_id)

    related = neo4j_client.get_related_facts(fact.fact_id)
    assert related['fact'] is not None
    assert len(related['syntheses']) == 1
    assert related['syntheses'][0]['synthesis_id'] == synthesis_id


def test_search_facts_by_ticker(neo4j_client):
    """Test ticker-based fact search."""
    episode_id = 'search_episode'
    neo4j_client.create_episode(
        episode_id=episode_id,
        query_text='Find AAPL valuation',
        created_at=datetime.now(UTC)
    )

    fact = VerifiedFact(
        fact_id='search_fact_aapl',
        query_id=episode_id,
        plan_id='plan_search',
        code_hash='hash_search',
        status='success',
        extracted_values={'ticker': 'AAPL', 'pe_ratio': 25.1},
        execution_time_ms=1200,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC),
        statement='AAPL PE ratio is 25.1'
    )
    neo4j_client.create_verified_fact_node(fact)
    neo4j_client.link_episode_to_fact(episode_id, fact.fact_id)

    results = neo4j_client.search_facts_by_ticker('AAPL', limit=10)
    assert len(results) >= 1
    assert any(item['fact_id'] == 'search_fact_aapl' for item in results)


def test_list_episodes_pagination(neo4j_client):
    """Test listing episodes with limit/offset."""
    for i in range(3):
        neo4j_client.create_episode(
            episode_id=f'episode_list_{i}',
            query_text=f'List test {i}',
            created_at=datetime.now(UTC)
        )

    episodes = neo4j_client.list_episodes(limit=2, offset=0)
    assert len(episodes) == 2
    assert all('episode_id' in item for item in episodes)


def test_get_related_facts_with_lineage(neo4j_client):
    """Test related facts returns lineage neighbors."""
    fact_a = VerifiedFact(
        fact_id='related_fact_a',
        query_id='related_query',
        plan_id='plan_a',
        code_hash='hash_a',
        status='success',
        extracted_values={'value': 100},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    fact_b = VerifiedFact(
        fact_id='related_fact_b',
        query_id='related_query',
        plan_id='plan_b',
        code_hash='hash_b',
        status='success',
        extracted_values={'value': 200},
        execution_time_ms=1100,
        memory_used_mb=31.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact_a)
    neo4j_client.create_verified_fact_node(fact_b)
    neo4j_client.create_lineage(from_fact_id='related_fact_b', to_fact_id='related_fact_a')

    related = neo4j_client.get_related_facts('related_fact_b')
    assert related['fact']['fact_id'] == 'related_fact_b'
    assert len(related['ancestors']) == 1
    assert related['ancestors'][0]['fact_id'] == 'related_fact_a'


# ==============================================================================
# Success Criteria Test
# ==============================================================================

def test_week3_day4_success_criteria(neo4j_client):
    """
    Week 3 Day 4 Success Criteria:

    - [x] Neo4j connection and initialization
    - [x] Create Episode nodes
    - [x] Create VerifiedFact nodes
    - [x] Link Episode→VerifiedFact (GENERATED)
    - [x] Query facts by Episode
    - [x] Lineage tracking (DERIVED_FROM)
    - [x] Cypher queries for audit trail
    - [x] Graph statistics
    """
    # Test 1: Create Episode
    neo4j_client.create_episode(
        episode_id='criteria_episode',
        query_text='Criteria test',
        created_at=datetime.now(UTC)
    )

    # Test 2: Create VerifiedFact
    fact = VerifiedFact(
        fact_id='criteria_fact',
        query_id='criteria_episode',
        plan_id='criteria_plan',
        code_hash='criteria_hash',
        status='success',
        extracted_values={'test': 123},
        execution_time_ms=1000,
        memory_used_mb=30.0,
        created_at=datetime.now(UTC)
    )
    neo4j_client.create_verified_fact_node(fact)

    # Test 3: Link them
    neo4j_client.link_episode_to_fact('criteria_episode', fact.fact_id)

    # Test 4: Query
    facts = neo4j_client.get_facts_for_episode('criteria_episode')
    assert len(facts) >= 1

    # Test 5: Graph stats
    stats = neo4j_client.get_graph_stats()
    assert stats['episode_count'] >= 1

    print("""
    ✅ Week 3 Day 4 SUCCESS CRITERIA:
    - Neo4j connection: ✅
    - Episode nodes: ✅
    - VerifiedFact nodes: ✅
    - Episode→Fact linking: ✅
    - Fact queries: ✅
    - Lineage tracking: ✅
    - Cypher queries: ✅
    - Graph stats: ✅
    """)
