"use client"

/**
 * Disclaimer Banner Component
 *
 * Week 11 Day 3: Legal compliance component
 *
 * Displays legal disclaimer banner at top of dashboard.
 * Can be dismissed but will reappear on page reload.
 */

import { useState, useEffect } from 'react'
import { AlertTriangle, X, ExternalLink } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface DisclaimerBannerProps {
  /**
   * Show full disclaimer text (default: false = condensed version)
   */
  fullText?: boolean

  /**
   * Allow dismissing the banner (default: true)
   */
  dismissible?: boolean

  /**
   * Variant style
   */
  variant?: 'warning' | 'info'
}

export default function DisclaimerBanner({
  fullText = false,
  dismissible = true,
  variant = 'warning'
}: DisclaimerBannerProps) {
  const [isDismissed, setIsDismissed] = useState(false)

  // Check if user has previously dismissed
  useEffect(() => {
    const dismissed = localStorage.getItem('disclaimer_dismissed')
    if (dismissed === 'true') {
      setIsDismissed(true)
    }
  }, [])

  const handleDismiss = () => {
    setIsDismissed(true)
    localStorage.setItem('disclaimer_dismissed', 'true')
  }

  if (isDismissed && dismissible) {
    return null
  }

  const bgColor = variant === 'warning'
    ? 'bg-yellow-50 dark:bg-yellow-950/20 border-yellow-200 dark:border-yellow-900'
    : 'bg-blue-50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-900'

  const iconColor = variant === 'warning'
    ? 'text-yellow-600 dark:text-yellow-500'
    : 'text-blue-600 dark:text-blue-500'

  const textColor = variant === 'warning'
    ? 'text-yellow-900 dark:text-yellow-100'
    : 'text-blue-900 dark:text-blue-100'

  return (
    <div className={`${bgColor} border rounded-lg p-4 mb-6 relative`}>
      <div className="flex items-start gap-3">
        {/* Icon */}
        <AlertTriangle className={`${iconColor} flex-shrink-0 mt-0.5`} size={20} />

        {/* Content */}
        <div className="flex-1">
          <h3 className={`font-semibold ${textColor} mb-1`}>
            Important Legal Disclaimer
          </h3>

          {fullText ? (
            <div className={`text-sm ${textColor} space-y-2`}>
              <p>
                <strong>This analysis is generated by an AI system and is provided for informational and educational purposes only.</strong>
                {' '}It does NOT constitute investment advice, financial advice, trading advice, or any other form of professional advice.
              </p>
              <p className="font-semibold">
                ⚠️ AI Disclosure: This content was generated by artificial intelligence (LLM-based multi-agent debate system).
                The system uses multiple AI models that may disagree with each other. Confidence scores reflect model agreement, NOT probability of accuracy.
              </p>
              <p>
                AI-generated analysis may contain errors, hallucinations, or outdated information.
                Market data may be delayed up to 15 minutes and sourced from public APIs (yfinance, FRED).
                VeriFind does not guarantee data accuracy or completeness.
              </p>
              <p className="font-medium">
                Always consult a qualified financial advisor before making investment decisions. Past performance does not guarantee future results.
              </p>
              <ul className="list-disc list-inside space-y-1 mt-2">
                <li>AI-generated analysis may contain hallucinations or errors</li>
                <li>Data sources may be delayed (up to 15 min), incomplete, or inaccurate</li>
                <li>Confidence scores reflect model agreement, NOT accuracy probability</li>
                <li>Past performance does not predict future results</li>
                <li>No professional advisor-client relationship is created</li>
                <li>VeriFind accepts no liability for losses arising from this analysis</li>
              </ul>
              <div className="mt-3 text-[10px] opacity-70">
                <p>Disclaimer v2.0 | SEC §202(a)(11) | EU AI Act Compliant</p>
              </div>
              <div className="mt-3">
                <a
                  href="/api/disclaimer"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-sm font-medium hover:underline"
                >
                  Read full legal disclaimer
                  <ExternalLink size={14} />
                </a>
              </div>
            </div>
          ) : (
            <p className={`text-sm ${textColor}`}>
              <strong>⚠️ AI-Generated Analysis:</strong> This is NOT investment advice. AI may contain errors or hallucinations.
              Confidence scores reflect model agreement, NOT accuracy. Data may be delayed up to 15 min.
              {' '}Always consult a qualified financial advisor before making investment decisions.
              {' '}
              <a
                href="/api/disclaimer"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-0.5 font-medium hover:underline"
              >
                Full disclaimer (v2.0)
                <ExternalLink size={12} />
              </a>
            </p>
          )}
        </div>

        {/* Dismiss button */}
        {dismissible && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleDismiss}
            className={`flex-shrink-0 ${iconColor} hover:bg-yellow-100 dark:hover:bg-yellow-900/30`}
            aria-label="Dismiss disclaimer"
          >
            <X size={18} />
          </Button>
        )}
      </div>
    </div>
  )
}


/**
 * Compact Disclaimer Footer
 *
 * For use at bottom of results/analysis pages
 */
export function DisclaimerFooter() {
  return (
    <div className="text-xs text-muted-foreground border-t pt-4 mt-8">
      <p className="flex items-center gap-1">
        <AlertTriangle size={12} className="flex-shrink-0" />
        <span>
          <strong>Disclaimer:</strong> This analysis is for informational purposes only and does not constitute financial advice.
          Past performance does not guarantee future results.
          {' '}
          <a
            href="/api/disclaimer"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:no-underline"
          >
            Full disclaimer
          </a>
        </span>
      </p>
    </div>
  )
}


/**
 * Disclaimer Modal Trigger
 *
 * Button to open full disclaimer in modal
 */
export function DisclaimerLink({ className = "" }: { className?: string }) {
  return (
    <a
      href="/api/disclaimer"
      target="_blank"
      rel="noopener noreferrer"
      className={`inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors ${className}`}
    >
      <AlertTriangle size={14} />
      Legal Disclaimer
      <ExternalLink size={12} />
    </a>
  )
}
